// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.2
// source: message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UptimeRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ProxyServer string                 `protobuf:"bytes,1,opt,name=proxy_server,json=proxyServer,proto3" json:"proxy_server,omitempty"`
	SentTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_time,json=sentTime,proto3" json:"sent_time,omitempty"`
	Ipv4        string                 `protobuf:"bytes,3,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	// Types that are valid to be assigned to OptionalIpv6:
	//
	//	*UptimeRequest_Ipv6
	OptionalIpv6 isUptimeRequest_OptionalIpv6 `protobuf_oneof:"optional_ipv6"`
	MacAddr      string                       `protobuf:"bytes,5,opt,name=mac_addr,json=macAddr,proto3" json:"mac_addr,omitempty"`
	// Types that are valid to be assigned to OptionalHostname:
	//
	//	*UptimeRequest_Hostname
	OptionalHostname isUptimeRequest_OptionalHostname `protobuf_oneof:"optional_hostname"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UptimeRequest) Reset() {
	*x = UptimeRequest{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UptimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UptimeRequest) ProtoMessage() {}

func (x *UptimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UptimeRequest.ProtoReflect.Descriptor instead.
func (*UptimeRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *UptimeRequest) GetProxyServer() string {
	if x != nil {
		return x.ProxyServer
	}
	return ""
}

func (x *UptimeRequest) GetSentTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SentTime
	}
	return nil
}

func (x *UptimeRequest) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *UptimeRequest) GetOptionalIpv6() isUptimeRequest_OptionalIpv6 {
	if x != nil {
		return x.OptionalIpv6
	}
	return nil
}

func (x *UptimeRequest) GetIpv6() string {
	if x != nil {
		if x, ok := x.OptionalIpv6.(*UptimeRequest_Ipv6); ok {
			return x.Ipv6
		}
	}
	return ""
}

func (x *UptimeRequest) GetMacAddr() string {
	if x != nil {
		return x.MacAddr
	}
	return ""
}

func (x *UptimeRequest) GetOptionalHostname() isUptimeRequest_OptionalHostname {
	if x != nil {
		return x.OptionalHostname
	}
	return nil
}

func (x *UptimeRequest) GetHostname() string {
	if x != nil {
		if x, ok := x.OptionalHostname.(*UptimeRequest_Hostname); ok {
			return x.Hostname
		}
	}
	return ""
}

type isUptimeRequest_OptionalIpv6 interface {
	isUptimeRequest_OptionalIpv6()
}

type UptimeRequest_Ipv6 struct {
	Ipv6 string `protobuf:"bytes,4,opt,name=ipv6,proto3,oneof"`
}

func (*UptimeRequest_Ipv6) isUptimeRequest_OptionalIpv6() {}

type isUptimeRequest_OptionalHostname interface {
	isUptimeRequest_OptionalHostname()
}

type UptimeRequest_Hostname struct {
	Hostname string `protobuf:"bytes,6,opt,name=hostname,proto3,oneof"`
}

func (*UptimeRequest_Hostname) isUptimeRequest_OptionalHostname() {}

type UptimeResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ProxyServer string                 `protobuf:"bytes,1,opt,name=proxy_server,json=proxyServer,proto3" json:"proxy_server,omitempty"`
	SentTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_time,json=sentTime,proto3" json:"sent_time,omitempty"`
	Ipv4        string                 `protobuf:"bytes,3,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	// Types that are valid to be assigned to OptionalIpv6:
	//
	//	*UptimeResponse_Ipv6
	OptionalIpv6 isUptimeResponse_OptionalIpv6 `protobuf_oneof:"optional_ipv6"`
	MacAddr      string                        `protobuf:"bytes,5,opt,name=mac_addr,json=macAddr,proto3" json:"mac_addr,omitempty"`
	// Types that are valid to be assigned to OptionalHostname:
	//
	//	*UptimeResponse_Hostname
	OptionalHostname isUptimeResponse_OptionalHostname `protobuf_oneof:"optional_hostname"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UptimeResponse) Reset() {
	*x = UptimeResponse{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UptimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UptimeResponse) ProtoMessage() {}

func (x *UptimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UptimeResponse.ProtoReflect.Descriptor instead.
func (*UptimeResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *UptimeResponse) GetProxyServer() string {
	if x != nil {
		return x.ProxyServer
	}
	return ""
}

func (x *UptimeResponse) GetSentTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SentTime
	}
	return nil
}

func (x *UptimeResponse) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *UptimeResponse) GetOptionalIpv6() isUptimeResponse_OptionalIpv6 {
	if x != nil {
		return x.OptionalIpv6
	}
	return nil
}

func (x *UptimeResponse) GetIpv6() string {
	if x != nil {
		if x, ok := x.OptionalIpv6.(*UptimeResponse_Ipv6); ok {
			return x.Ipv6
		}
	}
	return ""
}

func (x *UptimeResponse) GetMacAddr() string {
	if x != nil {
		return x.MacAddr
	}
	return ""
}

func (x *UptimeResponse) GetOptionalHostname() isUptimeResponse_OptionalHostname {
	if x != nil {
		return x.OptionalHostname
	}
	return nil
}

func (x *UptimeResponse) GetHostname() string {
	if x != nil {
		if x, ok := x.OptionalHostname.(*UptimeResponse_Hostname); ok {
			return x.Hostname
		}
	}
	return ""
}

type isUptimeResponse_OptionalIpv6 interface {
	isUptimeResponse_OptionalIpv6()
}

type UptimeResponse_Ipv6 struct {
	Ipv6 string `protobuf:"bytes,4,opt,name=ipv6,proto3,oneof"`
}

func (*UptimeResponse_Ipv6) isUptimeResponse_OptionalIpv6() {}

type isUptimeResponse_OptionalHostname interface {
	isUptimeResponse_OptionalHostname()
}

type UptimeResponse_Hostname struct {
	Hostname string `protobuf:"bytes,6,opt,name=hostname,proto3,oneof"`
}

func (*UptimeResponse_Hostname) isUptimeResponse_OptionalHostname() {}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf4, 0x01, 0x0a, 0x0d, 0x55, 0x70, 0x74,
	0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x37, 0x0a,
	0x09, 0x73, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x73, 0x65,
	0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x70, 0x76, 0x34, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x70, 0x76, 0x34, 0x12, 0x14, 0x0a, 0x04, 0x69, 0x70,
	0x76, 0x36, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x69, 0x70, 0x76, 0x36,
	0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x70, 0x76, 0x36, 0x42, 0x13, 0x0a, 0x11, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0xf5, 0x01, 0x0a, 0x0e, 0x55, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x69, 0x70, 0x76, 0x34, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x70,
	0x76, 0x34, 0x12, 0x14, 0x0a, 0x04, 0x69, 0x70, 0x76, 0x36, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x04, 0x69, 0x70, 0x76, 0x36, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x63, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x63, 0x41,
	0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d,
	0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x70,
	0x76, 0x36, 0x42, 0x13, 0x0a, 0x11, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x68,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x53, 0x0a, 0x0d, 0x55, 0x70, 0x74, 0x69, 0x6d,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64,
	0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x15, 0x2e,
	0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x55, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x55, 0x70,
	0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08,
	0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_proto_goTypes = []any{
	(*UptimeRequest)(nil),         // 0: uptime.UptimeRequest
	(*UptimeResponse)(nil),        // 1: uptime.UptimeResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_message_proto_depIdxs = []int32{
	2, // 0: uptime.UptimeRequest.sent_time:type_name -> google.protobuf.Timestamp
	2, // 1: uptime.UptimeResponse.sent_time:type_name -> google.protobuf.Timestamp
	0, // 2: uptime.UptimeService.SendCollectedData:input_type -> uptime.UptimeRequest
	1, // 3: uptime.UptimeService.SendCollectedData:output_type -> uptime.UptimeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_message_proto_msgTypes[0].OneofWrappers = []any{
		(*UptimeRequest_Ipv6)(nil),
		(*UptimeRequest_Hostname)(nil),
	}
	file_message_proto_msgTypes[1].OneofWrappers = []any{
		(*UptimeResponse_Ipv6)(nil),
		(*UptimeResponse_Hostname)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
