// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: message.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UptimeService_SendCollectedData_FullMethodName = "/uptime.UptimeService/SendCollectedData"
)

// UptimeServiceClient is the client API for UptimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UptimeServiceClient interface {
	SendCollectedData(ctx context.Context, in *UptimeRequest, opts ...grpc.CallOption) (*UptimeResponse, error)
}

type uptimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUptimeServiceClient(cc grpc.ClientConnInterface) UptimeServiceClient {
	return &uptimeServiceClient{cc}
}

func (c *uptimeServiceClient) SendCollectedData(ctx context.Context, in *UptimeRequest, opts ...grpc.CallOption) (*UptimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UptimeResponse)
	err := c.cc.Invoke(ctx, UptimeService_SendCollectedData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UptimeServiceServer is the server API for UptimeService service.
// All implementations must embed UnimplementedUptimeServiceServer
// for forward compatibility.
type UptimeServiceServer interface {
	SendCollectedData(context.Context, *UptimeRequest) (*UptimeResponse, error)
	mustEmbedUnimplementedUptimeServiceServer()
}

// UnimplementedUptimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUptimeServiceServer struct{}

func (UnimplementedUptimeServiceServer) SendCollectedData(context.Context, *UptimeRequest) (*UptimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCollectedData not implemented")
}
func (UnimplementedUptimeServiceServer) mustEmbedUnimplementedUptimeServiceServer() {}
func (UnimplementedUptimeServiceServer) testEmbeddedByValue()                       {}

// UnsafeUptimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UptimeServiceServer will
// result in compilation errors.
type UnsafeUptimeServiceServer interface {
	mustEmbedUnimplementedUptimeServiceServer()
}

func RegisterUptimeServiceServer(s grpc.ServiceRegistrar, srv UptimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedUptimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UptimeService_ServiceDesc, srv)
}

func _UptimeService_SendCollectedData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UptimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UptimeServiceServer).SendCollectedData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UptimeService_SendCollectedData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UptimeServiceServer).SendCollectedData(ctx, req.(*UptimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UptimeService_ServiceDesc is the grpc.ServiceDesc for UptimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UptimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uptime.UptimeService",
	HandlerType: (*UptimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCollectedData",
			Handler:    _UptimeService_SendCollectedData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
